[package]
name = "chalk-engine"
version = "0.4.0"
description = "Core trait engine from Chalk project"
license = "Apache-2.0/MIT"
authors = ["Rust Compiler Team", "Chalk developers"]
repository = "https://github.com/rust-lang-nursery/chalk"
readme = "README.md"
keywords = ["compiler", "traits", "prolog"]

[features]
default = ["stack_protection", "stabler"]
stack_protection = ["stacker"]
stabler = ["fxhash"]

[dependencies]
stacker = { version = "0.1.2", optional = true }
fxhash = { version = "0.2.1", optional = true }

[dependencies.chalk-macros]
version = "0.1.0"
path = "../chalk-macros"
